services:
  postgres:
    container_name: postgres-replicache
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: replicache
      POSTGRES_PASSWORD: postgres

  redis:
    container_name: redis-replicache
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  nats_data:
  redis_data:
