const ONE_MINUTE = 60;
const ONE_HOUR = 60 * ONE_MINUTE;
const ONE_DAY = 24 * ONE_HOUR;
const ONE_MONTH = 30 * ONE_DAY;
const ONE_YEAR = 12 * ONE_MONTH;

export const TIME_WINDOWS = {
  ONE_MINUTE,
  ONE_HOUR,
  ONE_DAY,
  ONE_MONTH,
  ONE_YEAR,
};
